name: cow_log
description: "A new Flutter project."
publish_to: 'none' # private project
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^2.5.1   # Added Lottie package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cow_animation.json   # Updated to Lottie JSON
    - assets/cow_animation2.json
    - assets/cow_animation3.json